import { StyleSheet } from 'react-native';

import Colors from '@/themes/colors';
import {
  bodyFontFamily,
  displayFontFamily,
  titleFontFamily,
} from '@/themes/typography';
import { cardSurface, primaryButton, primaryButtonText } from '@/themes/ui';

export const styles = StyleSheet.create({
  absoluteFill: {
    ...StyleSheet.absoluteFillObject,
  },
  backgroundRoot: {
    flex: 1,
    backgroundColor: '#F6F3EE',
  },
  backgroundWash: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.42,
  },
  backgroundContent: {
    flex: 1,
    position: 'relative',
    zIndex: 1,
  },
  diagonalBandOne: {
    position: 'absolute',
    top: -40,
    right: -90,
    width: 280,
    height: 640,
    backgroundColor: 'rgba(31,31,31,0.035)',
    transform: [{ rotate: '22deg' }],
  },
  diagonalBandTwo: {
    position: 'absolute',
    top: 180,
    left: -120,
    width: 260,
    height: 560,
    backgroundColor: 'rgba(45,190,139,0.06)',
    transform: [{ rotate: '-18deg' }],
  },
  diagonalBandThree: {
    position: 'absolute',
    bottom: -80,
    right: 10,
    width: 220,
    height: 420,
    backgroundColor: 'rgba(255,107,138,0.055)',
    transform: [{ rotate: '28deg' }],
  },
  container: {
    flex: 1,
  },
  centered: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  stateCard: {
    ...cardSurface,
    width: '100%',
    maxWidth: 360,
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 28,
    backgroundColor: 'rgba(255,255,255,0.92)',
  },
  stateIconWrap: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: '#EEF4F0',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
  },
  stateTitle: {
    fontSize: 22,
    lineHeight: 28,
    fontFamily: titleFontFamily,
    fontWeight: '700',
    color: '#1F1F1F',
    textAlign: 'center',
  },
  stateSubtitle: {
    marginTop: 8,
    fontSize: 15,
    lineHeight: 22,
    fontFamily: bodyFontFamily,
    color: 'rgba(31,31,31,0.62)',
    textAlign: 'center',
  },
  retryButton: {
    ...primaryButton,
    marginTop: 18,
    minHeight: 48,
    paddingHorizontal: 24,
  },
  retryText: {
    ...primaryButtonText,
    fontFamily: titleFontFamily,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 6,
  },
  headerCopy: {
    flex: 1,
  },
  headerTitle: {
    fontSize: 24,
    lineHeight: 29,
    fontFamily: displayFontFamily,
    fontWeight: '700',
    color: '#1F1F1F',
    letterSpacing: 0,
  },
  headerSubtitle: {
    marginTop: 2,
    fontSize: 13,
    lineHeight: 18,
    fontFamily: bodyFontFamily,
    color: 'rgba(31,31,31,0.62)',
  },
  remainingPill: {
    backgroundColor: '#1F1F1F',
    borderRadius: 16,
    paddingHorizontal: 11,
    paddingVertical: 8,
    alignItems: 'center',
    minWidth: 70,
  },
  remainingValue: {
    fontSize: 18,
    lineHeight: 22,
    fontFamily: titleFontFamily,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  remainingLabel: {
    marginTop: 2,
    fontSize: 11,
    fontFamily: bodyFontFamily,
    color: 'rgba(255,255,255,0.76)',
  },
  progressWrap: {
    paddingHorizontal: 20,
    paddingBottom: 2,
    gap: 6,
  },
  progressTrack: {
    height: 7,
    overflow: 'hidden',
    borderRadius: 99,
    backgroundColor: 'rgba(31,31,31,0.08)',
  },
  progressFill: {
    height: 7,
    borderRadius: 99,
    backgroundColor: Colors.accent.primary,
  },
  progressText: {
    fontSize: 12,
    fontFamily: bodyFontFamily,
    color: 'rgba(31,31,31,0.56)',
  },
  cardArea: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingTop: 10,
    paddingBottom: 0,
  },
  cardShadowBackMost: {
    position: 'absolute',
    width: '82%',
    height: 388,
    backgroundColor: 'rgba(31,31,31,0.07)',
    borderRadius: 26,
    transform: [{ translateX: -8 }, { translateY: 20 }, { rotate: '-3deg' }],
  },
  cardShadowBack: {
    position: 'absolute',
    width: '85%',
    height: 390,
    ...cardSurface,
    backgroundColor: 'rgba(255,255,255,0.72)',
    borderRadius: 26,
    paddingHorizontal: 22,
    paddingTop: 24,
    opacity: 0.98,
    transform: [{ translateX: 10 }, { translateY: 12 }, { rotate: '2deg' }],
  },
  card: {
    width: '90%',
    height: 404,
    ...cardSurface,
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
    borderRadius: 26,
    paddingHorizontal: 18,
    paddingVertical: 16,
    borderWidth: 1,
    borderColor: 'rgba(31,31,31,0.08)',
    shadowColor: '#5C5148',
    shadowOpacity: 0.18,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 16 },
    elevation: 9,
  },
  cardPressArea: {
    flex: 1,
  },
  overlay: {
    position: 'absolute',
    top: 66,
    alignSelf: 'center',
    minWidth: 172,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 18,
    zIndex: 10,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    borderWidth: 1,
  },
  likeOverlay: {
    backgroundColor: 'rgba(236,253,245,0.94)',
    borderColor: 'rgba(15,138,98,0.20)',
  },
  nopeOverlay: {
    backgroundColor: 'rgba(255,241,242,0.94)',
    borderColor: 'rgba(180,35,72,0.18)',
  },
  likeLabel: {
    fontSize: 18,
    fontWeight: '700',
    fontFamily: titleFontFamily,
    color: '#0F8A62',
    letterSpacing: 0,
  },
  nopeLabel: {
    fontSize: 18,
    fontWeight: '700',
    fontFamily: titleFontFamily,
    color: '#B42348',
    letterSpacing: 0,
  },
  cardGradient: {
    ...StyleSheet.absoluteFillObject,
  },
  cardTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
    marginBottom: 14,
  },
  cardTopLeft: {
    flex: 1,
    gap: 8,
  },
  sectorTag: {
    alignSelf: 'flex-start',
    maxWidth: '100%',
    backgroundColor: 'rgba(45,190,139,0.11)',
    borderRadius: 999,
    paddingHorizontal: 11,
    paddingVertical: 6,
  },
  sectorText: {
    fontSize: 12,
    fontFamily: titleFontFamily,
    color: '#0F6F50',
    fontWeight: '600',
  },
  heroPanel: {
    height: 224,
    backgroundColor: '#F7F8F5',
    borderRadius: 20,
    paddingHorizontal: 20,
    paddingVertical: 22,
    justifyContent: 'flex-start',
    overflow: 'hidden',
  },
  titleAccent: {
    width: 46,
    height: 5,
    borderRadius: 99,
    backgroundColor: Colors.accent.primary,
    marginBottom: 22,
  },
  cardTitle: {
    fontSize: 29,
    lineHeight: 35,
    fontFamily: titleFontFamily,
    fontWeight: '700',
    color: '#1F1F1F',
    letterSpacing: 0,
  },
  tagsSection: {
    minHeight: 36,
    paddingTop: 9,
  },
  tagsRow: {
    flexDirection: 'row',
    flexWrap: 'nowrap',
    gap: 8,
  },
  tag: {
    maxWidth: '100%',
    backgroundColor: 'rgba(31,31,31,0.06)',
    borderRadius: 999,
    paddingHorizontal: 11,
    paddingVertical: 6,
  },
  tagText: {
    fontSize: 12,
    lineHeight: 16,
    fontFamily: titleFontFamily,
    color: 'rgba(31,31,31,0.72)',
    fontWeight: '600',
  },
  cardFooter: {
    marginTop: 12,
    minHeight: 48,
    borderRadius: 18,
    backgroundColor: '#1F1F1F',
    paddingHorizontal: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  footerButton: {
    flex: 1,
  },
  footerText: {
    fontSize: 14,
    fontFamily: titleFontFamily,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  footerIcon: {
    marginLeft: 10,
  },
  buttons: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 28,
    paddingTop: 8,
    paddingBottom: 18,
  },
  actionBtn: {
    width: 68,
    height: 68,
    borderRadius: 34,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#5C5148',
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 7 },
    elevation: 6,
  },
  dislikeBtn: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: 'rgba(31,31,31,0.09)',
  },
  likeBtn: {
    backgroundColor: Colors.accent.primary,
  },
});
