import { StyleSheet } from 'react-native';

import Colors from '@/themes/colors';
import { bodyFontFamily, titleFontFamily } from '@/themes/typography';
import { cardSurface, primaryButton, primaryButtonText } from '@/themes/ui';

export const styles = StyleSheet.create({
  absoluteFill: {
    ...StyleSheet.absoluteFillObject,
  },
  backgroundRoot: {
    flex: 1,
    backgroundColor: '#F6F3EE',
  },
  backgroundWash: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.32,
  },
  backgroundContent: {
    flex: 1,
    position: 'relative',
    zIndex: 1,
  },
  diagonalBandOne: {
    position: 'absolute',
    top: -40,
    right: -90,
    width: 280,
    height: 640,
    backgroundColor: 'rgba(31,31,31,0.025)',
    transform: [{ rotate: '22deg' }],
  },
  diagonalBandTwo: {
    position: 'absolute',
    top: 180,
    left: -120,
    width: 260,
    height: 560,
    backgroundColor: 'rgba(255,255,255,0.18)',
    transform: [{ rotate: '-18deg' }],
  },
  diagonalBandThree: {
    position: 'absolute',
    bottom: -80,
    right: 10,
    width: 220,
    height: 420,
    backgroundColor: 'rgba(0,81,58,0.035)',
    transform: [{ rotate: '28deg' }],
  },
  container: {
    flex: 1,
  },
  centered: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  stateCard: {
    ...cardSurface,
    width: '100%',
    maxWidth: 360,
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 28,
    backgroundColor: 'rgba(255,255,255,0.92)',
  },
  stateIconWrap: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: '#EEF4F0',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
  },
  stateTitle: {
    fontSize: 22,
    lineHeight: 28,
    fontFamily: titleFontFamily,
    fontWeight: '700',
    color: '#1F1F1F',
    textAlign: 'center',
  },
  stateSubtitle: {
    marginTop: 8,
    fontSize: 15,
    lineHeight: 22,
    fontFamily: bodyFontFamily,
    color: 'rgba(31,31,31,0.62)',
    textAlign: 'center',
  },
  retryButton: {
    ...primaryButton,
    marginTop: 18,
    minHeight: 48,
    paddingHorizontal: 24,
  },
  retryText: {
    ...primaryButtonText,
    fontFamily: titleFontFamily,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 14,
  },
  headerCopy: {
    flex: 1,
  },
  headerEyebrow: {
    marginBottom: 6,
    fontSize: 13,
    lineHeight: 16,
    fontFamily: titleFontFamily,
    fontWeight: '700',
    color: Colors.accent.primary,
  },
  headerTitle: {
    fontSize: 28,
    lineHeight: 34,
    fontFamily: titleFontFamily,
    fontWeight: '600',
    color: '#1F1F1F',
    letterSpacing: 0,
  },
  headerSubtitle: {
    marginTop: 4,
    fontSize: 16,
    lineHeight: 22,
    fontFamily: bodyFontFamily,
    color: 'rgba(31,31,31,0.62)',
  },
  remainingPill: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    paddingHorizontal: 13,
    paddingVertical: 10,
    alignItems: 'center',
    minWidth: 72,
    borderWidth: 1,
    borderColor: 'rgba(0,81,58,0.14)',
    shadowColor: '#5C5148',
    shadowOpacity: 0.08,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  remainingValue: {
    fontSize: 22,
    lineHeight: 26,
    fontFamily: titleFontFamily,
    fontWeight: '600',
    color: Colors.accent.primary,
  },
  remainingLabel: {
    marginTop: 1,
    fontSize: 11,
    fontFamily: bodyFontFamily,
    color: 'rgba(31,31,31,0.56)',
  },
  progressWrap: {
    paddingHorizontal: 24,
    paddingBottom: 14,
    gap: 8,
  },
  progressTrack: {
    height: 7,
    overflow: 'hidden',
    borderRadius: 99,
    backgroundColor: 'rgba(31,31,31,0.08)',
  },
  progressFill: {
    height: 7,
    borderRadius: 99,
    backgroundColor: Colors.accent.primary,
  },
  progressMeta: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  progressText: {
    fontSize: 13,
    fontFamily: bodyFontFamily,
    color: 'rgba(31,31,31,0.56)',
  },
  progressValue: {
    fontSize: 13,
    fontFamily: titleFontFamily,
    fontWeight: '600',
    color: Colors.accent.primary,
  },
  cardArea: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingTop: 2,
    paddingBottom: 0,
  },
  cardShadowBackMost: {
    position: 'absolute',
    width: '82%',
    height: 388,
    backgroundColor: 'rgba(0,81,58,0.07)',
    borderRadius: 8,
    transform: [{ translateX: -8 }, { translateY: 18 }, { rotate: '-2deg' }],
  },
  cardShadowBack: {
    position: 'absolute',
    width: '85%',
    height: 390,
    ...cardSurface,
    backgroundColor: 'rgba(255,255,255,0.72)',
    borderRadius: 8,
    paddingHorizontal: 22,
    paddingTop: 24,
    opacity: 0.98,
    transform: [{ translateX: 8 }, { translateY: 10 }, { rotate: '1.5deg' }],
  },
  card: {
    width: '90%',
    height: 400,
    ...cardSurface,
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
    borderRadius: 8,
    paddingHorizontal: 18,
    paddingVertical: 16,
    borderWidth: 1,
    borderColor: 'rgba(0,81,58,0.10)',
    shadowColor: '#5C5148',
    shadowOpacity: 0.13,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 16 },
    elevation: 9,
  },
  cardPressArea: {
    flex: 1,
    overflow: 'hidden',
  },
  overlay: {
    position: 'absolute',
    top: 66,
    alignSelf: 'center',
    minWidth: 172,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 8,
    zIndex: 10,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    borderWidth: 1,
  },
  likeOverlay: {
    backgroundColor: 'rgba(236,253,245,0.94)',
    borderColor: 'rgba(15,138,98,0.20)',
  },
  nopeOverlay: {
    backgroundColor: 'rgba(255,241,242,0.94)',
    borderColor: 'rgba(180,35,72,0.18)',
  },
  likeLabel: {
    fontSize: 18,
    fontWeight: '700',
    fontFamily: titleFontFamily,
    color: '#0F8A62',
    letterSpacing: 0,
  },
  nopeLabel: {
    fontSize: 18,
    fontWeight: '700',
    fontFamily: titleFontFamily,
    color: '#B42348',
    letterSpacing: 0,
  },
  cardGradient: {
    ...StyleSheet.absoluteFillObject,
  },
  cardTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
    marginBottom: 14,
  },
  cardTopLeft: {
    flex: 1,
    gap: 8,
  },
  sectorTag: {
    alignSelf: 'flex-start',
    maxWidth: '100%',
    backgroundColor: 'rgba(45,190,139,0.11)',
    borderRadius: 999,
    paddingHorizontal: 11,
    paddingVertical: 6,
  },
  sectorText: {
    fontSize: 12,
    fontFamily: titleFontFamily,
    color: '#0F6F50',
    fontWeight: '600',
  },
  heroPanel: {
    height: 168,
    backgroundColor: '#F7FAF8',
    borderRadius: 8,
    paddingHorizontal: 20,
    paddingVertical: 22,
    justifyContent: 'flex-start',
    overflow: 'hidden',
  },
  titleAccentWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 20,
  },
  titleAccent: {
    width: 46,
    height: 5,
    borderRadius: 99,
    backgroundColor: Colors.accent.primary,
  },
  cardKicker: {
    fontSize: 12,
    lineHeight: 15,
    fontFamily: titleFontFamily,
    fontWeight: '600',
    color: 'rgba(31,31,31,0.48)',
  },
  cardTitle: {
    fontSize: 25,
    lineHeight: 31,
    fontFamily: titleFontFamily,
    fontWeight: '600',
    color: '#1F1F1F',
    letterSpacing: 0,
  },
  tagsSection: {
    minHeight: 74,
    maxHeight: 74,
    paddingTop: 10,
    overflow: 'hidden',
  },
  tagsTitle: {
    marginBottom: 7,
    fontSize: 12,
    lineHeight: 15,
    fontFamily: titleFontFamily,
    fontWeight: '600',
    color: 'rgba(31,31,31,0.48)',
  },
  tagsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    maxHeight: 34,
    overflow: 'hidden',
  },
  tag: {
    maxWidth: '82%',
    backgroundColor: 'rgba(31,31,31,0.06)',
    borderRadius: 999,
    paddingHorizontal: 11,
    paddingVertical: 6,
  },
  tagText: {
    fontSize: 12,
    lineHeight: 16,
    fontFamily: titleFontFamily,
    color: 'rgba(31,31,31,0.72)',
    fontWeight: '600',
  },
  tagCount: {
    minWidth: 34,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(0,81,58,0.10)',
    alignItems: 'center',
  },
  tagCountText: {
    fontSize: 12,
    lineHeight: 16,
    fontFamily: titleFontFamily,
    color: Colors.accent.primary,
    fontWeight: '700',
  },
  cardFooter: {
    marginTop: 'auto',
    minHeight: 42,
    paddingHorizontal: 18,
    borderRadius: 21,
    alignSelf: 'flex-start',
  },
  buttons: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 24,
    paddingTop: 10,
    paddingBottom: 20,
  },
  actionBtn: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#5C5148',
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 7 },
    elevation: 6,
  },
  dislikeBtn: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: 'rgba(180,35,72,0.10)',
  },
  likeBtn: {
    backgroundColor: Colors.accent.primary,
  },
});
